# @format

version: '3.7'
services:
    mongodb_container:
        container_name: mongo_db_juze_sauerlach
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_AUTH}
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
volumes:
    mongodb_data_container:
