# @format
name: CI & Deploy
on:
    push:
        branches: ['main']
jobs:
    ci:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: CI setup
              run: yarn ci
            - name: Build application
              run: yarn build:prod
              env:
                  NODE_ENV: production
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: testing ssh connection to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: 22
                  script: |
                      bash /srv/juzesauerlach/deploy.sh
